"""Base probe interface for TeleMesh Watcher Node."""

import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Callable

logger = logging.getLogger(__name__)


@dataclass
class ProbeEvent:
    """Event generated by a probe."""

    source: str
    probe: str
    timestamp: float = field(default_factory=time.time)
    event: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert event to dictionary for JSON serialization."""
        return {
            "source": self.source,
            "probe": self.probe,
            "timestamp": self.timestamp,
            "event": self.event,
        }


class BaseProbe(ABC):
    """Abstract base class for all probes."""

    def __init__(self, source_id: str = "watcher-001"):
        """Initialize probe with source identifier."""
        self.source_id = source_id
        self._running = False
        self._on_event: Callable[[ProbeEvent], None] | None = None

    @property
    def on_event(self) -> Callable[[ProbeEvent], None] | None:
        """Get the event callback."""
        return self._on_event

    @on_event.setter
    def on_event(self, callback: Callable[[ProbeEvent], None]) -> None:
        """Set the event callback."""
        self._on_event = callback

    def emit_event(self, event_data: dict) -> None:
        """Emit an event to the registered callback."""
        if self._on_event is None:
            logger.warning("No event callback registered for %s", self.probe_name)
            return

        event = ProbeEvent(
            source=self.source_id,
            probe=self.probe_name,
            event=event_data,
        )
        logger.debug("Emitting event: %s", event.to_dict())
        self._on_event(event)

    @property
    @abstractmethod
    def probe_name(self) -> str:
        """Return the name of this probe type."""
        pass

    @abstractmethod
    def start(self) -> None:
        """Start the probe monitoring."""
        pass

    @abstractmethod
    def stop(self) -> None:
        """Stop the probe monitoring."""
        pass

    def __enter__(self) -> "BaseProbe":
        """Context manager entry."""
        self.start()
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Context manager exit."""
        self.stop()
